name: CI Test Last Commit

on:
  push
env:
  SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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 # ${{ secrets.SLACK_WEBHOOK_UR }}

jobs:
  job1:
    uses: ./.github/workflows/test-workflow.yml
    with:
      webhook: https://hooks.slack.com/services/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 # ${{ secrets.SLACK_WEBHOOK_UR }}
    
  Test:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        angular-version:   
          - 12.0.5

    steps:
      - uses: actions/checkout@v2
        id: Checkout
        with:
          fetch-depth: 0
      
      # - name: Use Node.js 12.20.1
      #   uses: actions/setup-node@v2
      #   id: Setup-Node
      #   with:
      #     node-version: 12.20.1
      #     cache: "npm"      
      # - name: Cache node modules
      #   id: node-cache
      #   uses: actions/cache@v1
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      # - name: Install Angular Cli
      #   id: Install-Angular-Cli
      #   run: npm install -g @angular/cli@${{matrix.angular-version}}
      # - name: Installing dependencies
      #   run: npm ci --ignore-scripts
      # - name: Running linter
      #   id: Running-linter
      #   run: ng lint
      # - name: Running tests
      #   id: Running-tests
      #   run: ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          config: .github/slack.yml
        if: always()