name: CI Test Last Commit

on:
  push
env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  Test:
    uses: ./.github/workflows/test-workflow.yml
    with:
      webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
    
  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        angular-version:   
          - 14.0.4

    steps:
      - uses: actions/checkout@v2
        id: Checkout
        with:
          fetch-depth: 0
      
      - name: NG version
        run: ng version
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          config: .github/slack.yml
        if: always()